version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'crate-ci/typos'
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    # Don't specify version-strategy if https://github.com/dependabot/dependabot-core/issues/4009 was unstable state
    # At least 2026-09-18, "increase" option raised an error even after closed the issue :<
    # versioning-strategy: increase
