# https://taskfile.dev

version: '3'

env:
  # If test for nix product: `PLUGIN_PATH="$(fd --absolute-path plugin.wasm result)" task test`
  PLUGIN_PATH: '{{.USER_WORKING_DIR}}/target/wasm32-unknown-unknown/debug/dprint_plugin_typstyle.wasm'

tasks:
  default:
    deps:
      - check
      - test
  build: # Prefer cargo cache rather than go-task cache feature
    env:
      SKIP_BUILD: 'false' # Don't use "$CI" for this purpose
    status:
      - |
          [ "$SKIP_BUILD" == 'true' ]
    cmds:
      # Omit "--release" for development purpose. Release assets should use `nix build`
      - cargo build
  check:
    deps:
      - test
      - lint
  test:
    deps:
      - test-e2e-default
      - test-e2e-all
      - test-e2e-with_global_config
    # cmds:
    #   - cargo test # There is no test. If adding here, required to update GitHub Actions workflow
  test-e2e-*:
    deps:
      - build
    vars:
      TESTNAME: '{{index .MATCH 0}}'
    cmds:
      - cd 'tests/{{.TESTNAME}}' && dprint check --plugins="$PLUGIN_PATH" expected.typ
      - cd 'tests/{{.TESTNAME}}' && diff <(cat ../raw.typ | dprint fmt --stdin ../raw.typ --plugins="$PLUGIN_PATH") expected.typ
  bump-fixtures-*:
    deps:
      - build
    vars:
      TESTNAME: '{{index .MATCH 0}}'
    cmds:
      - cd 'tests/{{.TESTNAME}}' && cat ../raw.typ | dprint fmt --stdin ../raw.typ --plugins="$PLUGIN_PATH" > expected.typ
  bump-fixtures:
    deps:
      - bump-fixtures-default
      - bump-fixtures-all
      - bump-fixtures-with_global_config
  fmt:
    cmds:
      - cargo fmt
      - dprint fmt
      - git ls-files '*.nix' | xargs nix fmt
  lint:
    cmds:
      - cargo clippy
      - cargo fmt --check
      - dprint check
      - typos . .github .vscode
      # nix fmt doesn't have check: https://github.com/NixOS/nix/issues/6918
      - git ls-files '*.nix' | xargs nixfmt --check
      - git ls-files | xargs nix run github:kachick/selfup/v1.2.0 -- list -check
  selfup:
    cmds:
      - git ls-files | xargs nix run github:kachick/selfup/v1.2.0 -- run
  deps:
    cmds:
      - rustc --version
      - cargo --version
      - rust-analyzer --version
      - clippy-driver --version
      - rustfmt --version
      - dprint --version
      - nix --version
      - nil --version
      - nixfmt --version
      - task --version
      - typos --version
      - typst --version
      - typstyle --version
