name: 'Setup Nix with cache'
description: 'Install Nix and configure Nix store caching'
runs:
  using: 'composite'
  steps:
    - uses: NixOS/nix-installer-action@62c1943b776c509394b550f3f983adc14e9212d6 # v1.0.0
    - uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      with:
        diagnostic-endpoint: '' # Empty string disables telemetry
